### ISSUE TITLE
在heroku上部署好了，本地怎么启动

### ISSUE THREAD

**Issue by dapao9999** [mrluanma/shadowsocks-websocket-python#1]
大神本地怎么使用啊？

**Comment by mrluanma** [comment]
https://github.com/mrluanma/shadowsocks-heroku

**Comment by dapao9999** [comment]
那个我会了，这个shadowsocks-websocket-python的部署好后怎么使用？

**Comment by mrluanma** [comment]
这个仓库做的事情相当于 shadowsocks-heroku 里的 server.js，也就是说，这个仓库部署好之后，通过 heroku config 设置加密方式和密码（和 shadowsocks-heroku 一样），然后搭配 shadowsocks-heroku 里的 local.js 来使用。

**Comment by dapao9999** [comment]
感谢解答！明白了
