### ISSUE TITLE
可不可以在本地把链接转回shadowsocks

### ISSUE THREAD

**Issue by ly444983** [mrluanma/shadowsocks-websocket-python#2]
就是websockify 0.0.0.0:$PORT 127.0.0.1:$(($PORT+50))反过来
这样就可以使用大量现成的优秀的客户端

**Comment by onplus** [comment]
在本地运行一个ss server

**Comment by mrluanma** [comment]
一晃过去了很多年，现在有不少了。我尝试了[websocat](https://github.com/vi/websocat)，很好用。
