### ISSUE TITLE
这个项目能否使用？

### ISSUE THREAD

**Issue by the0demiurge** [mrluanma/shadowsocks-websocket-python#3]
node的客户端通用性太弱，所以我部署了一下本项目，但是我在heroku里面折腾了半天结果也连不上。请问这个项目能成功作为ss服务端吗，如果可以的话能写一个简单的使用说明吗？

**Comment by onplus** [comment]
这个还是通过websocket 的  
https://github.com/mrluanma/shadowsocks-websocket-python/issues/1#issuecomment-136154744
https://github.com/mrluanma/shadowsocks-websocket-python/blob/466d143018c892766efc237aa1e8b963705e0bb2/Procfile.honcho#L1


可以一键部署
https://github.com/onplus/shadowsocks-websocket-python/tree/deploy#shadowsocks-websocket-python

**Comment by the0demiurge** [comment]
这样的话还是需要专门的客户端，实在不太方便：）

**Comment by the0demiurge** [comment]
协议不一样，用不了的

On Oct 10, 2017 4:05 PM, "onplus" <notifications@github.com> wrote:

这个还是通过websocket 的
#1 (comment)
<https://github.com/mrluanma/shadowsocks-websocket-python/issues/1#issuecomment-136154744>
https://github.com/mrluanma/shadowsocks-websocket-python/blob/
466d143018c892766efc237aa1e8b963705e0bb2/Procfile.honcho#L1

可以一键部署
https://github.com/onplus/shadowsocks-websocket-python/
tree/deploy#shadowsocks-websocket-python

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrluanma/shadowsocks-websocket-python/issues/3#issuecomment-335394017>,
or mute the thread
